/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_axios@1.8.4_embla-carousel@8.5.2_encoding@0.1.13_jo_8d747c2c154b589481745e300f0b979b/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UForm: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_axios@1.8.4_embla-carousel@8.5.2_encoding@0.1.13_jo_8d747c2c154b589481745e300f0b979b/node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_axios@1.8.4_embla-carousel@8.5.2_encoding@0.1.13_jo_8d747c2c154b589481745e300f0b979b/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_axios@1.8.4_embla-carousel@8.5.2_encoding@0.1.13_jo_8d747c2c154b589481745e300f0b979b/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    ULinkBase: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_axios@1.8.4_embla-carousel@8.5.2_encoding@0.1.13_jo_8d747c2c154b589481745e300f0b979b/node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
